# Generated by Django 4.0.3 on 2022-03-24 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillStatus',
            fields=[
                ('name', models.CharField(choices=[('Pending', 'Pending'), ('Clear', 'Clear')], max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('name', models.CharField(choices=[('Supplier', 'Supplier'), ('Worker', 'Worker'), ('Customer', 'Customer'), ('Agency', 'Agency'), ('Model', 'Model')], max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('mobileNo', models.PositiveIntegerField(max_length=10, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=500, null=True)),
                ('organisationName', models.CharField(max_length=200, null=True)),
                ('agencyName', models.CharField(max_length=200, null=True)),
                ('organisationAddress', models.TextField(null=True)),
                ('agencyAddress', models.TextField(null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('social_github', models.CharField(blank=True, max_length=200, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('social_website', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.roll')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('username', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.profile')),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.roll')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.billstatus')),
            ],
        ),
    ]
