# Generated by Django 4.0.3 on 2022-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0002_alter_supplier_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
